### ISSUE TITLE
[feat] Support for webview overlay

### ISSUE THREAD

**Issue by ghost** [pykeio/millennium#11]
Could there be a function to overlay a separate webview ontop of the current one, just like electron's BrowserView class, this could be used to code browsers etc... in millennium if an IFrame is not enough. This also alows usage of devtools etc..

**Comment by sudo-carson** [comment]
This would require a total rewrite of `millennium-webview`, and I'm not totally sure if it would be possible cross-platform.

I've been experimenting with implementing `<webview>`s like Electron; you could use that when (and if) it's released. But I'm not too confident I could do it on the Rust side.

It could maybe be achieved with child borderless windows but that would be a pain to work with...

**Comment by sudo-carson** [comment]
After a little bit of research, no, this is not at all possible. Millennium is not Electron, we don't have full control over the browser window, only limited APIs that are given to us. For something like a web browser, I'd recommend looking at CEF instead. It has loads more control because, like Electron, it embeds Chromium.

You could use iframes, but it's not sandboxed or isolated (scripts in the iframe will still run on the window's main thread), or you could use child borderless windows, but those aren't very elegant (or safe) solutions. Millennium was designed for apps, not something as advanced as a web browser.

**Comment by XFaonAE** [comment]
Well after looking through the code, it seems very very very possible, just like you have the initial webview right? Well add two of thos, just make them overlap with absolute positioning
